#%RAML 1.0 DataType

properties:
  id:
    type: number
    required: true
  firstName:
    type: string
    minLength: 2
    required: true
  lastName:
    type: string
    minLength: 2
    required: true
  email:
    type: string
    required: true
    pattern: ^.+@.+\..+$