#%RAML 1.0 ResourceType
post?:
  is:
    - header-client-credentials-required
  description: Create an account in Salesforce
  body:
    application/json:
      type: account-request
      example: !include /account/examples/account-request-example.raml
  responses:
    201:
      body:
        application/json:

put?:
  is:
    - header-client-credentials-required
  description: Update an account in Salesforce
  body:
    application/json:
      type: account-request
      example: !include /account/examples/account-request-example.raml
  responses:
    201:
      body:
        application/json:

get?:
  is:
    - header-client-credentials-required
  description: Retrieve an account object from Salesforce
  responses:
    200:
      body:
        application/json:
          example: !include /account/examples/get-account-response-example.raml

delete?:
  is:
    - header-client-credentials-required
  description: Deletes an account object from Salesforce
  responses:
    200:
      body:
        application/json: