#%RAML 1.0
baseUri: https://mocksvc.mulesoft.com/mocks/c5f55550-8d61-424a-9301-25d14b0fd50f
title: backend-api-01
description: This a sample backend API to prepare Proxy API demo
version: 1.0

uses:
  cics: traits/client_id_secret.raml
  basicAuth: traits/basicAuth.raml
  createEmp: dataTypes/createEmployeeType.raml
  
/createEmployee:
    is: [cics.client_id_secret, basicAuth.basic_auth]
    post:
      description: Post Employee details
      body:
        application/json:
           type: createEmp.Employee
      responses:
        201:
          body:
            application/json:
              example:
                {
                   "createdId": "123e4567-e89b-12d3-a456-42661417",
                   "creationTime": "2019-08-26T13:32:10.64-07:00",
                   "message": "Employee details stored successfully"
                }
        400:
          body:
            application/json:
              example:
                {
                  "code": 1000,
                   "message": "Employee details can not store"
                }
                
/getEmployee:
    is: [cics.client_id_secret]
    get:
      description: Get Employee details
      queryParameters:
        employeeId:
          description: employeeID
          type: number
          required: true
      responses:
        200:
          body:
            application/json:
               example: |
                {"EmployeeID":1,"EmployeeName":"Ankur Bhuyan", "Email":"webmail.ajb@ankuran.online"}
        400:
          body:
            application/json:
              example:
                {
                  "code": 1001,
                   "message": "Employee id is not recognized"
                }
                
/deleteEmployee:
    is: [cics.client_id_secret]
    delete:
      description: Delete Employee details
      queryParameters:
        employeeId:
          description: employeeID
          type: number
          required: true
      responses:
        200:
          body:
            application/json:
               example: |
                {message: "Employee details delete successfully"}
        400:
          body:
            application/json:
              example:
                {
                  "code": 1001,
                   "message": "Employee id is not recognized"
                }