#%RAML 1.0
baseUri: https://mocksvc.mulesoft.com/mocks/c5f55550-8d61-424a-9301-25d14b0fd50f
title: backend-api-02
description: This a sample backend API to prepare Proxy API demo
version: 1.0

uses:
  cics: traits/client_id_secret.raml
  blogReq: dataTypes/BlogRequestType.raml
  validRes: dataTypes/validBlogResponse.raml
  invalidRes: dataTypes/invalidBlogResponse.raml
              
/mulesoftBlog:
    is: [cics.client_id_secret]
    post:
      description: Post Mulesoft Blog details
      body:
        application/xml:
          type: blogReq.root
      responses:
        201:
          body:
            application/json:
              type: validRes.Blog
        400:
          body:
            application/json:
              type: invalidRes.Blog
                
/springBlog:
    is: [cics.client_id_secret]
    put:
      description: Post Php Blog details
      body:
        application/x-www-form-urlencoded:
          type: blogReq.root
      responses:
        201:
          body:
            application/json:
              type: validRes.Blog
        400:
          body:
            application/json:
              type: invalidRes.Blog