#%RAML 1.0 Library
traits:
 client_id_secret:
  headers:
    client_id:
      required: true
      description: Client id is mandatory to something
      example: "enfjjwdweewo3123jcis382f"
    client_secret:
      required: true
      description: Client secret is mandatory to get something
      example: "fwfjowpeufu83fufu2f83f238r32r"