#%RAML 1.0 Library
types:
  root:
    properties:
      creatorFirstName:
        required: true
        type: string
      creatorLastName:
        required: true
        type: string
      email:
        required: true
        type: string
      gender:
        required: true
        type: string
      phone:
        required: true
        type: number
      organization:
        required: true
        type: string