#%RAML 1.0 NamedExample
{
    "name": "Ankur",
    "email": "ankur.bhuyan@gmail.com",
    "number": "3333344444",
    "phone": "9590951206",
    "fax": "21312312",
    "billingAddress": {
        "street": "1255 26TH ST",
        "city": "Bangalore",
        "state": "Karnataka",
        "postalCode": "560032",
        "countryCode": "IN"
    },
    "shippingAddress": {
        "street": "Teacher's Colony",
        "city": "Lilongwe",
        "state": "Dedza",
        "postalCode": "999999",
        "countryCode": "MW"
    }
}