<definitions xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd" xmlns:wsp="http://www.w3.org/ns/ws-policy" xmlns:wsp1_2="http://schemas.xmlsoap.org/ws/2004/09/policy" xmlns:wsam="http://www.w3.org/2007/05/addressing/metadata" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:tns="http://ankuran.online/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns="http://schemas.xmlsoap.org/wsdl/" targetNamespace="http://ankuran.online/" name="PersonServiceImplService">
  <message name="requestedPersonInfo">
    <part name="firstName" type="xsd:string" />
    <part name="middleName" type="xsd:string" />
    <part name="lastName" type="xsd:string" />
    <part name="gender" type="xsd:string" />
    <part name="phone" type="xsd:int" />
  </message>
  <message name="requestedPersonInfoResponse">
    <part name="id" type="xsd:string" />
    <part name="message" type="xsd:string" />
  </message>
  <portType name="PersonServiceI">
    <operation name="requestedPersonInfo">
      <input message="tns:requestedPersonInfo" />
      <output message="tns:requestedPersonInfoResponse" />
    </operation>
  </portType>
  <binding name="PersonServiceImplPortBinding" type="tns:PersonServiceI">
    <soap:binding transport="http://schemas.xmlsoap.org/soap/http" style="document" />
    <operation name="requestedPersonInfo">
      <soap:operation soapAction="" />
      <input>
        <soap:body use="literal" />
      </input>
      <output>
        <soap:body use="literal" />
      </output>
    </operation>
  </binding>
  <service name="PersonServiceImplService">
    <port name="PersonServiceImplPort" binding="tns:PersonServiceImplPortBinding">
      <soap:address location="http://www.examples.com/personServer" />
    </port>
  </service>
</definitions>