#%RAML 1.0 ResourceType
post?:
  is:
    - header-client-credentials-required
  description: Create an account in Salesforce
  body:
    application/json:
      type: account-request
      example: !include /account/examples/account-request-example.raml
  responses:
    201:
      body:
        application/json:
          type: account-response
          example: !include /account/examples/create-account-response-example.raml

put?:
  is:
    - header-client-credentials-required
  description: Create an account in Salesforce
  body:
    application/json:
      type: account-request
      example: !include /account/examples/account-request-example.raml
  responses:
    201:
      body:
        application/json:
          type: account-response
          example: !include /account/examples/update-account-response-example.raml