#%RAML 1.0
baseUri: https://mocksvc.mulesoft.com/mocks/c5f55550-8d61-424a-9301-25d14b0fd50f
title: proxy-api
description: This REST API is to behave like an proxy API in between client and source system
version: 1.0

uses:
  jsonSchema: schemas/request-mapping.raml
  xmlSchema: schemas/request-xml-mapping.raml         
  
/callBackend:
    post:
      description: Post endpoint details
      body:
        application/json:
          type: jsonSchema.Request
        application/xml:
          type: xmlSchema.root
        application/x-www-form-urlencoded: