#%RAML 1.0

title: mule-4.4.0-api
description: This API is to explore the new changes in Mule 4.4.0
version: v0

types:
  user_register: !include dataTypes/register.raml
  
/mdc:
  description: This endpoints to test mdc logging capabilities of mule version 4.4.0
  /settingAndRemovingVariables:
    description: This endpoint to test MDC logging with setting and removing logging variables
    post:
      body:
        application/json:
          type: user_register
      responses:
        200:
          body:
            application/json:
            
  /settingAndCleaningVariables:
    description: This endpoint to test MDC logging with setting and cleaning logging variables
    post:
      body:
        application/json:
          type: user_register
      responses:
        200:
          body:
            application/json:
            
  /loggingWithCorrelationId:
    description: This endpoint to test MDC logging with correlationId update
    post:
      body:
        application/json:
          type: user_register
      responses:
        200:
          body:
            application/json:
          
/dataweave:
  description: This endpoints to test mdc new dataweave capabilities of mule version 4.4.0
  /indexOf:
    description: This endpoint to test new function called "indexOf"
    post:
      responses:
        200:
          body:
            application/json:
  /lastIndexOf:
    description: This endpoint to test new function called "lastIndexOf"
    post:
      responses:
        200:
          body:
            application/json:
  /onNull:
    description: This endpoint to test new function called "onNull"
    post:
      responses:
        200:
          body:
            application/json:
  /then:
    description: This endpoint to test new function called "then"
    post:
      responses:
        200:
          body:
            application/json:
  /collapse:
    description: This endpoint to test new function called "collapse"
    post:
      responses:
        200:
          body:
            application/json:
  /countCharactersBy:
    description: This endpoint to test new function called "countCharactersBy"
    post:
      responses:
        200:
          body:
            application/json:
  /countMatches:
    description: This endpoint to test new function called "countMatches"
    post:
      responses:
        200:
          body:
            application/json:
  /everyCharacter:
    description: This endpoint to test new function called "everyCharacter"
    post:
      responses:
        200:
          body:
            application/json:
  /first:
    description: This endpoint to test new function called "first"
    post:
      responses:
        200:
          body:
            application/json:
  /last:
    description: This endpoint to test new function called "last"
    post:
      responses:
        200:
          body:
            application/json:
  /hammingDistance:
    description: This endpoint to test new function called "hammingDistance"
    post:
      responses:
        200:
          body:
            application/json:
  /levenshteinDistance:
    description: This endpoint to test new function called "levenshteinDistance"
    post:
      responses:
        200:
          body:
            application/json:
  /lines:
    description: This endpoint to test new function called "lines"
    post:
      responses:
        200:
          body:
            application/json:
  /mapString:
    description: This endpoint to test new function called "mapString"
    post:
      responses:
        200:
          body:
            application/json:
  /remove:
    description: This endpoint to test new function called "remove"
    post:
      responses:
        200:
          body:
            application/json:
  /reverse:
    description: This endpoint to test new function called "reverse"
    post:
      responses:
        200:
          body:
            application/json:
  /replaceall:
    description: This endpoint to test new function called "replaceall"
    post:
      responses:
        200:
          body:
            application/json:
  /someCharacter:
    description: This endpoint to test new function called "someCharacter"
    post:
      responses:
        200:
          body:
            application/json:
  /substring:
    description: This endpoint to test new function called "substring"
    post:
      responses:
        200:
          body:
            application/json:
  /substringBy:
    description: This endpoint to test new function called "substringBy"
    post:
      responses:
        200:
          body:
            application/json:
  /substringEvery:
    description: This endpoint to test new function called "substringEvery"
    post:
      responses:
        200:
          body:
            application/json:
  /words:
    description: This endpoint to test new function called "words"
    post:
      responses:
        200:
          body:
            application/json: