#%RAML 1.0 Library

traits:
  requestInfo:
    queryParameters:
      firstName:
          displayName: firstName
          type: string
          description: First name of user
          example: "Ankur"
          required: true
      lastName:
          displayName: lastName
          type: string
          description: Last name of user
          example: "Bhuyan"
          required: true
      email:
          displayName: email
          type: string
          pattern: ^.+@.+\..+$
          description: Email id of user
          example: "ab@ankuran.online"
          required: true
      country:
          displayName: country
          type: string
          description: Country of user
          example: "India"
          required: true
      created:
          displayName: created date time
          type: datetime-only
          description: Country of user
          example: 2021-08-21T21:00:00
          required: true
     