#%RAML 1.0

title: dynamic-schema-validation
description: This API is to give example how we can use country based Json Schema for validation
version: v0

  
/userRegister:
  description: This endpoint to store the Data of user in Database
  post:
    responses:
      200:
        body:
          application/json:
  