#%RAML 1.0

title: duplicate-check-api
description: This API is to give example how we can restrict duplicate request payload
version: v0

types:
  user_register: !include dataTypes/register.raml
  
/user_register:
  description: This endpoint to store the Data of user in Database
  post:
    body:
        application/json:
          type: user_register
    responses:
      200:
        body:
          application/json: