#%RAML 1.0 Trait
    headers:
      client_id:
        type: string
        description: Client Id for the respective consumer application
      client_secret:
        type: string
        description: Client Secret for the respective consumer application