#%RAML 1.0 Library
#This library defines the health resource type
resourceTypes:
  health:
    usage: Use this resource to check health of Mulesoft application
    description: Entity representing a Mulesoft application health
    get:
      description: Get health of an application