#%RAML 1.0 Trait
    responses:
      500:
        body:
          application/xml:
            type: !include ../../../data-types/standard-response.raml
            example: !include ../../../examples/errors/500.raml