#%RAML 1.0 Library
types:
  root:
    properties:
      host:
        required: true
        enum: ["backend01", "backend02" ]
      method:
        required: true
        enum: ["GET", "POST", "PUT", "DELETE", "PATCH" ]
      endpoint:
        required: true
        type: string
      forwarder-content-type:
        type: string
      body:
        type: any[]