#%RAML 1.0 Library
types:
  Address:
    properties:
      isCurrentAddress:
        required: true
        type: boolean
      street:
        required: true
        type: string
      city:
        required: true
        type: string
      district:
        required: true
        type: string
      pin:
        required: true
        type: number
      country:
        required: true
        type: string